### ISSUE TITLE
Bug | Review and fix failing `leverage version` command not working.

### ISSUE THREAD

**Issue by exequielrafaela** [binbashar/leverage#11]
## What? 
- Review and fix failing `leverage version` command not working.
- Probably related with mfa script which must be skipped for certain tasks.

```bash
╭─    ~/Binbash/repos/Leverage/ref-architecture/le-tf-infra-aws  on   master ····················································································································· ✔  at 10:11:39 
╰─ leverage version
[DEBUG] Found config file: /Users/exequielbarrirero/Binbash/repos/Leverage/ref-architecture/le-tf-infra-aws/build.env
[ build.py - Starting task "_checkdir" ]
This task cannot be run from root path
[ build.py - Error in task "_checkdir" ]
[ build.py - Aborting build ]
```

## Why?
- Fix command and improve UX.

**Comment by angelofenoglio** [comment]
Is this based on a `version` task defined on a build script?

If the expected output is `leverage, version [0-9]+.[0-9]+.[0-9]+` then the correct command would be `leverage --version`.

**Comment by exequielrafaela** [comment]
@angelofenoglio I think the command was based on the legacy behavior. What about now? If we run `leverage --version` under any scope we'll get the expected version right? If that's the case please feel free to close this issue. Thanks!

CC: @diego-ojeda-binbash

**Comment by exequielrafaela** [comment]
@angelofenoglio @diego-ojeda-binbash No sure if can close this issue based on my aforementioned review.

**Comment by angelofenoglio** [comment]
Sorry for the late reply.
Yes, based on the current behaviour, `leverage --version` will print the version without failing under any scope.
`leverage version` on the other hand is, by design, not a command, so it will simply not be recognized.
I think we can close this issue safely.

**Comment by exequielrafaela** [comment]
@angelofenoglio Angelo thanks for your quick response proceeding to close this issue as RESOLVED 💪🏼
