### ISSUE TITLE
Feature | support `leverage terraform apply --all-layers` command

### ISSUE THREAD

**Issue by exequielrafaela** [binbashar/leverage#123]
## What? 

- ✅ 1st iteration of a new `leverage` cli feature will that be intended for the EKS layers:
  - https://github.com/binbashar/le-tf-infra-aws/tree/master/apps-devstg/us-east-1/k8s-eks
  - https://github.com/binbashar/le-tf-infra-aws/tree/master/apps-devstg/us-east-1/k8s-eks-demoapps

Add support for the following tentative commands

### Alternative 1

- ~~`leverage terraform init-all/plan-all/apply-all`~~
- `leverage terraform init-all/plan-all/apply-all --layers=network,cluster,identities,k8s-components,k8s-workloads`

### Alternative 2

- ~~`leverage terraform init/plan/apply --all-layers`~~
- `leverage terraform init/plan/apply --layers=network,cluster,identities,k8s-components,k8s-workloads`

**CONDERATION:**  This feature should be compatible with different multi-layer execution workflows where the same layer could be optionally executed more than once if needed.

## Why?

- Significantly improved DX / UX for binbash Leverage Referece architecture customer projects.

## Extra info

- https://binbash.atlassian.net/wiki/spaces/BDPS/pages/2196799489/Product+Roadmap+2022

**Comment by juanmatias** [comment]
created branch ISSUE-123-all-layers-option

**Comment by exequielrafaela** [comment]
@juanmatias For the moment will not support the `--all-layers` flag, but we confirm that we'll start supporting the `leverage terraform init/plan/apply --layers=network,cluster,identities,k8s-components,k8s-workloads` command.

CC: @angelofenoglio @diego-ojeda-binbash

**Comment by juanmatias** [comment]
changes for 'all layers' option are in the following PR https://github.com/binbashar/leverage/pull/151

Before it is merged this other has to be merged: https://github.com/binbashar/leverage/pull/149

**Comment by juanmatias** [comment]
Done in CLI v1.9.1

**Comment by exequielrafaela** [comment]
@juanmatias thanks!
