### ISSUE TITLE
Feature | leverage support kubectl

### ISSUE THREAD

**Issue by marianod92** [binbashar/leverage#126]
## What?

Add the ability to manage / configure `kubectl` with the necessary AWS configuration from **leverage-cli**

Leverage cli generates subfolders within `~/.aws/` based on the project name for the creation/update of AWS Configs and Credentials files

```
~/.aws/[PROJECT]/config
~/.aws/[PROJECT]/credentials
```

When you need to perform actions on a cluster (EKS), besides setting the corresponding context/cluster, it is necessary to export the AWS configuration files, the AWS profile and the location of the `.kubeconfig` file.

- For example:

  ```
  export AWS_CONFIG_FILE=~/.aws/[PROJECT]/config
  export AWS_SHARED_CREDENTIALS_FILE=~/.aws/[PROJECT]/credentials
  export KUBECONFIG=~/.kube/[PROJECT]/apps-devstg
  export AWS_PROFILE=[PROJECT]-apps-devstg-devops
  ```

Perhaps being able to support a leverage setting of some of these variables would improve the experience and agility of using leverage to generate the required kubeconfig files/contexts.

### Alternative
- `leverage kubectl configure`
- `leverage kubectl switch / set`

### Extra Info
- https://github.com/ahmetb/kubectx
- https://github.com/cloudnativelabs/kube-shell

**Comment by exequielrafaela** [comment]
@marianod92 @juanmatias @diego-ojeda-binbash @angelofenoglio I'll add some related comments based on our slack thread:

### Related issue

Currently to generate the AWS SSO credentials to work with `kubectl` AWS SSO integration, which is the standard **leverage cli** workflow auth method, it will always imply to go to the corresponding layer and run `leverage aws configure sso` || `leverage aws sso login` to generate / renew credentials and be able to continue working.


### Possible solution

@diego-ojeda-binbash proposed an alternative more automated approach which could look something similar to: 

> "perhaps something like `leverage k8s token --cluster [NAME]` that we add to the `kubeconfig` file in order to get the k8s token automatically

**Comment by angelofenoglio** [comment]
A tool that may help managing multiple kubectl versions in a single workstation is [asdf](https://github.com/asdf-vm/asdf) with the [kubectl plugin](https://github.com/asdf-community/asdf-kubectl), as explained in [this guide](https://vishnudeva.medium.com/managing-multiple-kubectl-versions-shorts-4973e0e2d24).

**Comment by Franr** [comment]
While working on this, we brought up the question of how to test and develop new commands without installing the CLI locally.
It is expected to document the answer as part of this ticket.

**Comment by exequielrafaela** [comment]
Thanks for your comment addressing this matter @Franr! 📚 🚀
