### ISSUE TITLE
Enhancement | Refactor CLI SSO workflow to favor the reuse of the access token

### ISSUE THREAD

**Issue by diego-ojeda-binbash** [binbashar/leverage#130]
## Describe the Feature

__Description edited 2022/11/28 based on Leverage CLI planning meeting.__

Reuse, whenever possible, the existing SSO token to fetch different needed roles.

IMPORTANT: this applies mainly to how we currently use 2 different tokens, one for the management layers, and another for the non-management layers. So we should revisit those flows, what do we actually want to enforce by that, find the best trade-off between security and UX.

## Expected Behavior

When an SSO token is still live, because it was obtained using SSO for a given Leverage CLI account, and the CLI is used in another account, for a different role that has no valid credentials, try to use the SSO token in order to assume the role before fail.

## Use Case

Given the case:
- Leverage CLI is used in account A
- A role is defined for this account: let's say `role_A`
- Leverage CLI detects: 
  - no temporary token for the given role
- Leverage CLI asks the user to perform an SSO login 
- With the SSO token Leverage CLI fetches the credentials for `role_A`
- Then Leverage CLI is used in account B
- A different role is defined for this account: let's say `role_B`
- Leverage CLI detects: 
  - no credentials for the given role
- Leverage CLI asks the user to perform an SSO login 

Leverage CLI is storing these two tokens in different places, one for `role_A` and another for `role_B`.

Using SSO, it is likely the same SSO login (which creates a session), to have access to assume both roles.

So it makes sense to do the following last steps instead of the previous ones:

- Then Leverage CLI is used in account B
- A different role is defined for this account: let's say `role_B`
- Leverage CLI detects: 
  - no credentials for the given role
- Leverage CLI tries to use the existing SSO temporary credentials in order to get access to the role in account B
- If it fails then it asks the user to perform a new SSO login
- If it succeeds it uses the account B credentials for whatever the command was submitted

## Describe Ideal Solution

Keeping in mind that:
- one single SSO login can have access to more than one role in different accounts
- Leverage CLI is storing the obtained tokens in different places, but
- any of these tokens is valid and has the same access permissions...

A possibility is to have Leverage CLI storing the credentials in a unique file, accessed when any of these roles are needed, and failing just in case the role can not be assumed.

The security should sit on the AWS side, where a given user (which can perform an SSO login) will have access to a given set of permissions (i.e. devops+admin, devops, readonly, etc)

## Alternatives Considered

Since the roles are set on a per-account basis, the credentials can be stored at account level.

This will force to re-login per account unless a more complex mechanism is used to keep creds per account and to keep a fallback creds per project.

E.g.:
```
root
  |----------role creds for: project
  |------management
                   |----------role creds for: M
  |------security
                   |----------role creds for: S
```

When logging into management, the creds for M are stored and since the creds for project does not exist, it overrides them.
Then when trying to use security account, CLI tries to read creds for S, since they does not exists it tries to retrieve cred for project, if it succeed, then stores creds for project in creds for S.

This is a draft of what it was mentioned.

## Additional Context

The login is [here](https://github.com/binbashar/le-docker-leverage-toolbox/blob/18b9163eb5297d26535e6a5ce2b0c9ebaa037ee6/scripts/aws-sso/aws-sso-entrypoint.sh#L87).

**Comment by exequielrafaela** [comment]
@diego-ojeda-binbash thanks for creating this very detailed and valuable issue, it would be a great UX/DX improvement based on users feedback.

**Comment by juanmatias** [comment]
also, it has to recognize the sso role to assume with no need of running aws configure sso again.

now, if the role is changed in the tf file, the configure nees to be run again, the idea is to get the role from the tf file instead of the aws config file (so we can switch accounts with different roles)

**Comment by juanmatias** [comment]
Done in Toolbox versions 1.2.7-0.1.0 and 1.3.5-0.0.1
