### ISSUE TITLE
Feature | Create set of test to ensure coverage, integration, etc

### ISSUE THREAD

**Issue by juanmatias** [binbashar/leverage#142]
## Describe the Feature

Create a set of automated tests to ensure coverage, integration, etc.

## Expected Behavior

This product should be granted in a set of known scenarios.

## Use Case

A user getting this tool should have a guarantee for the most common scenarios

## Describe Ideal Solution

Create a set of tests.
These tests have to be defined.
This issue is aimed to be a kickoff for this discussion.

## Alternatives Considered

n/a

## Additional Context

This also applies to Leverage Toolbox

**Comment by exequielrafaela** [comment]
@juanmatias could you please refine the definition of the purpose for this issue, since this wide scope results difficult to be understood and prioritized. 

CC: @diego-ojeda-binbash

**Comment by exequielrafaela** [comment]
We'll follow up this issue here => https://github.com/binbashar/leverage/issues/165#issuecomment-1956918674
