### ISSUE TITLE
Bug | Research on: CLI asks for OTP for each use

### ISSUE THREAD

**Issue by juanmatias** [binbashar/leverage#144]
## Describe the Bug

As per @exequielrafaela report, from version 1.8.0 and up, and when using IAM and MFA, the CLI requests OTP for each use.

## Expected Behavior

OTP should be requested only on revalidating credentials

## Steps to Reproduce
2. Run '....'
3. Enter '....'

## Screenshots

n/a

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: [e.g. Linux, OSX, WSL, etc]
 - Version [e.g. 10.15]

## Additional Context
n/a

**Comment by exequielrafaela** [comment]
We finally solved this issue by upgrading to the latest `leverage-toolbox`  [image](https://hub.docker.com/layers/binbash/leverage-toolbox/1.2.7-0.0.5/images/sha256-f68c8ba48362fa0ff54e2ba73fac6f735ad62f5f55fedba9869c548c7ebc5582?context=repo). Consider fixing this version at your [build.env](https://github.com/binbashar/le-tf-infra-aws/blob/93bcc4b14c671a79785b89195f096097e15af968/build.env#L8) as follows => `TERRAFORM_IMAGE_TAG=1.2.7-latest` or if needed force your docker image update by re downloading it.

CC: @juanmatias @diego-ojeda-binbash
