### ISSUE TITLE
Enhancement | Update AWS CLI in the docker toolbox image

### ISSUE THREAD

**Issue by diego-ojeda-binbash** [binbashar/leverage#148]
Use version ~= 2.7.32

EDIT: I think the problem we were having was with using the AWS CLI to generage the Kubernetes config file. I believe such file was generated with an old apiVersion, e.g. `apiVersion: client.authentication.k8s.io/v1beta1`. Updating the AWS CLI version should fix that.

**Comment by juanmatias** [comment]
An issue was opened in Toolbox repo for following this: https://github.com/binbashar/le-docker-leverage-toolbox/issues/30

**Comment by exequielrafaela** [comment]
@diego-ojeda-binbash @juanmatias we'll address this issue here => https://github.com/binbashar/le-docker-leverage-toolbox/issues/30
