### ISSUE TITLE
Feature | General code refactoring and doc improvement

### ISSUE THREAD

**Issue by exequielrafaela** [binbashar/leverage#16]
### What?

- ✅ **General code refactoring:** the goal is to make the code more readable and easier to maintain. For instance: extract part of code to separate files, reduce number of arguments in some functions, 
- ✅ **Improve documentation:** favor self-documented code first, but for the rest, add documentation to help make the code easier to understand.

For all the items above, let's focus on quick gains, that is, changes that are easy to spot and whose implementation will be completed in the same day. The idea is to target for modifications that are easy to achieve but which will yield important benefits. In other words, for now let's not focus on big changes; if we find those, let's create an issue in the repository so we can tackle them later on.

### ⭐ Writing Clean Code Challenges:
- Unclear requirements that change frequently
- Lack of clean code training 
- Lack of programming correction 
- Refactoring of code to clean-up frequently (non-priory factor)
- Sometimes project timelines hit the code quality

### ⭐ Qualities of Clean Code Development:
- Focused while writing Clean code
- Making it simple for writing program
- Code should not be redundant
- Reading code should be pleasant
- Easily extended by any other developer
- Minimal dependencies with other elements
- Smaller code helps developers to understand better
- Write unit and acceptance test cases in place

### Principle and Practices of Clean Code:
![image](https://user-images.githubusercontent.com/18539704/114579132-f1548980-9c53-11eb-998e-f2aa372411ec.png)

📚 **Source article:** https://dzone.com/articles/how-to-practice-clean-code-in-software-projects

**Comment by diego-ojeda-binbash** [comment]
First round can be found here: https://github.com/binbashar/leverage/pull/18

+ @exequielrafaela @angelofenoglio

**Comment by angelofenoglio** [comment]
#20 and #22 should have addressed the most of the remaining concerns of this issue. Maybe we could consider closing it? @diego-ojeda-binbash @exequielrafaela

**Comment by diego-ojeda-binbash** [comment]
> #20 and #22 should have addressed most of the remaining concerns of this issue. Maybe we could consider closing it? @diego-ojeda-binbash @exequielrafaela

@angelofenoglio Yes, please go ahead.

**Comment by exequielrafaela** [comment]
🚀 ❤️ 👏🏼
