### ISSUE TITLE
Enhancement | Improve tests for `--layers`

### ISSUE THREAD

**Issue by juanmatias** [binbashar/leverage#165]
## Describe the Feature

Once a second test layer is created (https://github.com/binbashar/le-tf-infra-aws/issues/466) implement the tests for making use of the `--layers` option with the created layers.

I.e. , use the option for `init`, `apply` and `destroy` all the test layers.

## Expected Behavior

The `--layers` option is tested for real.

## Use Case

n/a

## Describe Ideal Solution

n/a

## Alternatives Considered

n/a

## Additional Context

n/a

**Comment by exequielrafaela** [comment]
We'll follow-up based on this latets @Franr PR https://github.com/binbashar/leverage/pull/245 creating new tasks based on the coveralls.io data
