### ISSUE TITLE
Feature | add leverage cli unit and functional tests - 1st rounds

### ISSUE THREAD

**Issue by exequielrafaela** [binbashar/leverage#17]
### What? 

Let's start with a small set of tests. Just a few of them, say 3 or 4 to get us started and to help us figure out the best way to test the CLI.
Some of the general cases we could consider for such initial set of tests are:
- ✅ Run the CLI from a dir/subdir that is/is not part of a repository
- ✅ Run the CLI with/without a build file
- ✅ Test arguments parsing
- ✅ Test conf module
- ✅ Test path module

📒 **CONSIDERATION:** Let's also take a look at how **_Pynt_** wrote its test cases and let's also peek at how other projects that also forked from Pynt approached their testing needs.

### Why?
- ➕ Makes the Process Agile
- ➕ Quality of Code
- ➕ Finds Software Bugs Early
- ➕ Facilitates Changes and Simplifies Integration
- ➕ Provides Documentation
- ➕ Debugging Process
- ➕ Design
- ➕ Reduce Costs

📚 ref article: https://dzone.com/articles/top-8-benefits-of-unit-testing

**Comment by angelofenoglio** [comment]
First round of unit tests added here: #19

**Comment by exequielrafaela** [comment]
> The first round of unit tests had misguided definitions. This second round of tests will focus on creating actual unit tests for the following internal modules:
> - _parsing.py
> - conf.py
> - leverage.py
> - logging.py
> - path.py
> - task.py ?
> 
> Such unit tests should test the functions of said modules to verify their functionality is consistent along time. By taking this approach we should be able to reveal additional refactoring opportunities as some of the functions may prove hard to test in their current implementation.

**Comment by angelofenoglio** [comment]
Second round addressed in #20 as well as [this comment.](https://github.com/binbashar/leverage/pull/19#issuecomment-821274207)

**Comment by exequielrafaela** [comment]
As discussed along with @diego-ojeda-binbash and @angelofenoglio we must cover the following functional tests cases

- run the cli and there is no build.py
- run the cli with a build.py in the same dir
- run the cli with a build.py in a parent dir
- run a task and validate the output
- run the cli with a build.env in the same dir
- run the cli with a build.env in a parent dir
- run the cli with a build.env in the same dir and in a parent dir

**Comment by angelofenoglio** [comment]
All required test cases have been addressed in #22.

**Comment by exequielrafaela** [comment]
@angelofenoglio Everything looks great! Closing this issue based on your comment. Thanks!

CC: @diego-ojeda-binbash @binbashar/leverage-ref-architecture-aws-dev
