### ISSUE TITLE
Bug | Bad owner or permissions on /root/.ssh/config

### ISSUE THREAD

**Issue by juanmatias** [binbashar/leverage#173]
## Describe the Bug

When trying to init a layer, and using private ssh accessed repos, this error occurs:

```shell
Bad owner or permissions on /root/.ssh/config
```

Problem seems to be `.ssh/config` does not belongs to the user in the container (root) instead, the UID is the one of the user in the host machine.
 
Workaround:

* edit  ~/.ssh/config adding this
```yaml
host gitlab.com
 HostName gitlab.com
 IdentityFile ~/.ssh/filename
 User username
```
(this example is for gitlab.com, also replace the filename and user name)
* change ownership and permissions
```shell
sudo chown root:root ~/.ssh/config && sudo chmod 600 ~/.ssh/config
```
* run init as usual
```shell
leverage tf init
```

## Expected Behavior
Leverage to handle this situation.

## Steps to Reproduce
2. Run '....'
3. Enter '....'

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: [e.g. Linux, OSX, WSL, etc]
 - Version [e.g. 10.15]

**Comment by exequielrafaela** [comment]
@juanmatias we'll take your blog post as reference to improve this design https://juanmatiasdelacamara.wordpress.com/2019/04/07/ssh-keys-ssh-agent-and-docker/ ;)

**Comment by juanmatias** [comment]
new solution implemented, it has to be checked... no Toolbox change is needed here.

**Comment by exequielrafaela** [comment]
@juanmatias thanks for your update! So the PR https://github.com/binbashar/leverage/pull/174 is ready to review? Do we need to wait for the doc 1st?

CC: @angelofenoglio @Franr @diego-ojeda-binbash

**Comment by juanmatias** [comment]
https://github.com/binbashar/le-ref-architecture-doc/pull/156 and https://github.com/binbashar/leverage/pull/174 merged... closing

**Comment by exequielrafaela** [comment]
Reopening this issue since a customer reported it again:
- root permissions on the .aws/project_short dir probably related to a specific linux distro
- We should be able to run quick checks to verify those scenarios and show a warning at the very least
- ✅ **QUICK FIX:** run a chown after the `leverage` command similar to what we've done in the past => https://github.com/binbashar/le-dev-makefiles/blob/e478a17152a5abdd1649a269fbfa903d1bdb8a59/terraform1/terraform1.mk#L60

**Comment by diego-ojeda-binbash** [comment]
Functionality was tested during the last call. Docs and CI are remaining.
