### ISSUE TITLE
Bug | Leverage supposes there is a single MFA device

### ISSUE THREAD

**Issue by Franr** [binbashar/leverage#178]
## Describe the Bug
Now AWS let you assign [multiple MFA devices](https://aws.amazon.com/blogs/security/you-can-now-assign-multiple-mfa-devices-in-iam/). Leverage still supposes there is [one or zero](https://github.com/binbashar/leverage/blob/master/leverage/modules/credentials.py#L536-L538). And if there is one, it is supposes that you tagged it with [the same name](https://github.com/binbashar/le-tf-infra-aws/blob/b327a8e5b4eee60d49c01fe02e82b50594b32086/security/global/base-identities/groups_policies.tf#L260) of the user.

## Expected Behavior
Let you use multiple MFA devices with no restrictions around tagging.

## Screenshots
![mfa](https://user-images.githubusercontent.com/482506/223460362-e117e7f2-c7f9-481e-adc7-854b602fdc2f.png)

## Additional Context
- Security account bootstrapped from the landing zone documentation.

**Comment by exequielrafaela** [comment]
Since we're favoring IAM IdC (former SSO) auth mechanism we're not going to fix this issue. 
Consider there's a workaround for this issue, you have to create the Virtual MFA device with the same name as your IAM user.
Eg: 
- username: exequiel.barrirero
- mfa_device_name: exequiel.barrirero
