### ISSUE TITLE
Feature | Leverage created files ownership

### ISSUE THREAD

**Issue by juanmatias** [binbashar/leverage#191]
## Describe the Feature

When Leverage creates files, e.g. `.aws` or `.terraform`, it uses the container user, i.e. `root`. Thus, the created files are owned by it.

To use the files outside of Leverage (e.g. using the K8s generated credentials), an extra step has to be taken to change the ownership to the host UID.

To make it easy to use these files outside Leverage, it would be desirable they were owned by the host UID.

## Expected Behavior

The aforementioned files should be owned by the user using Leverage, so he/she can use them with no extra steps.

## Use Case

A user creating credentials for K8s and using them for accessing from outside Leverage.

## Additional Context

As per this chat: https://binbashar.slack.com/archives/GG0PJ78J3/p1681391685307179

**Comment by exequielrafaela** [comment]
Customer reported this issue under Linux OS:

- root permissions on the `.aws/project_short` dir probably related to a specific linux distro
- We should be able to run quick checks to verify those scenarios and show a warning at the very least
- ✅ QUICK FIX: run a chown after the leverage command similar to what we've done in the past => https://github.com/binbashar/le-dev-makefiles/blob/e478a17152a5abdd1649a269fbfa903d1bdb8a59/terraform1/terraform1.mk#L60

**Comment by exequielrafaela** [comment]
Released at https://github.com/binbashar/leverage/releases/tag/v1.10.1

**Comment by exequielrafaela** [comment]
@Franr related issue => https://binbashar.slack.com/archives/GG0PJ78J3/p1690992634211149
