### ISSUE TITLE
Feature | Enhance leverage CLI verbosity levels for easier troubleshooting

### ISSUE THREAD

**Issue by exequielrafaela** [binbashar/leverage#202]
## Describe the Feature
Enhance the verbosity levels of the CLI to improve user experience and simplify the troubleshooting process. This can be achieved by adding three verbosity levels:

- 🟢 **Default:** minimal output to indicate progress and confirm that the process is running smoothly.
- 🟡 **Friendly messages:** provide more descriptive messages to guide the user and help them find the issue without having to be an expert. This includes changing `"Attempting to get temporary credentials for security account"` to `"Looking for the profile bb-security-devops in the file ~/.aws/bb/config"` (or similar).
- 🔴 **Debug mode:** provide detailed output for advanced troubleshooting when the previous modes are insufficient to solve the problem. Users can run this mode and share the output with the team to get help.

## Expected Behavior
The CLI will have three different verbosity levels that users can choose from depending on their needs. By **default**, the CLI will output minimal information to confirm that the process is running smoothly. The **friendly message** level will provide more descriptive messages to guide the user and help them solve the issue without having to be an expert. The **debug mode** will provide detailed output for advanced troubleshooting when necessary.

## Use Case
This feature will benefit users who encounter issues with the CLI, especially those who are not experts in troubleshooting. By providing more descriptive messages and detailed output, users will be able to find and solve problems more easily and efficiently.

## Describe Ideal Solution
The ideal solution would be to add the three verbosity levels described above to the CLI. The user can select the desired level by using a flag or command-line option. For example, `--verbose=friendly` would enable friendly messages, and `--verbose=debug` would enable debug mode.

## Alternatives Considered
An alternative to this solution would be to continue documenting the credentials process in detail, but this approach can be pretty complicated and not user-friendly. By enhancing the verbosity levels, users can solve problems more intuitively and with less documentation.

## Additional Context
This feature will simplify the documentation process, reducing the need for detailed documentation about the credentials process. By using the friendly messages level, users can understand the process more easily and solve issues more efficiently. The debug mode will help the team collaborate more effectively by providing detailed output for advanced troubleshooting.

**Comment by exequielrafaela** [comment]
Ongoing discussions could be found here => https://binbashar.slack.com/archives/GG0PJ78J3/p1686668729191949

CC: @binbashar/leverage-ref-architecture-aws-admin @binbashar/leverage-ref-architecture-aws-dev

**Comment by Franr** [comment]
We decided to go with https://github.com/binbashar/le-docker-leverage-toolbox/pull/53 rather than https://github.com/binbashar/leverage/pull/208, for sake of simplicity.

The idea is to add extra information to the errors while they are reported, rather than being proactive, given the dimensions and variability of potential problems.
