### ISSUE TITLE
Bug | Docker daemon doesn't seem to be responding on Mac

### ISSUE THREAD

**Issue by Franr** [binbashar/leverage#221]
## Describe the Bug
If you run `leverage` on `version 24.0.6, build ed223bc` on Mac, apparently docker-py tries to connect to the docker socket on the wrong place.

## Expected Behavior
Rather than `/var/run/docker.sock`, we should try to establish the connection through `unix://$HOME/.docker/run/docker.sock` instead

## Environment (please complete the following information):

`Docker version 24.0.6, build ed223bc`
`leverage version 1.10.2`
`MacOS Ventura 13.5`

## Additional Context
https://github.com/docker/docker-py/issues/3146
https://docs.docker.com/desktop/release-notes/#4131
https://github.com/docker/for-mac/issues/6529
https://github.com/portainer/portainer/issues/9945#issuecomment-1654825596

**Comment by diego-ojeda-binbash** [comment]
Fixes to these issues have been documented here: https://github.com/binbashar/le-ref-architecture-doc/pull/194

**Comment by exequielrafaela** [comment]
@diego-ojeda-binbash, thank you for your collaboration on this project. I've just published the latest documentation release [here](https://github.com/binbashar/le-ref-architecture-doc/releases/tag/v1.0.2).

@kwesiRutledge
Kwesi, I appreciate your feedback immensely. It's fantastic to see that you're most probably utilizing Leverage for your AWS projects. I'd like to extend an invitation for you to join our community Slack channel. It's a great place for prompt support and collaborative discussions on any future needs you might have. You can join us [here](https://join.slack.com/t/binbashar/shared_invite/zt-fw1692b6-9k4ADsWJ47lKacszphXM1w).
