### ISSUE TITLE
Feature | Make build.py tasks composable similarly to how build.env can be combined

### ISSUE THREAD

**Issue by diego-ojeda-binbash** [binbashar/leverage#23]
Currently Leverage CLI supports multiple config files (build.env) to be combined/merged by placing them in current or parent directories. We would like to explore the possibility of having the same feature applied to the tasks defined in build files (build.py).

For instance, we could have the following directory layout:
```
.
├── build.py
└── subdir
    └── build.py

1 directory, 2 files
```
The `build.py` file at the root could have the following task definitions:
```
@task()
def hello():
  ...

@task()
def test():
  ...
```

And then `./subdir/build.py` file could have these other tasks:
```
@task()
def run():
  ...
```

So the combined `build.py` would end up having all three tasks. On the same line, build files in a subdirectory should be able to override task definitions.

**Comment by exequielrafaela** [comment]
As per our discussion along @diego-ojeda-binbash and @angelofenoglio, we'll close this issue and consider it to be re-opened in the future in case it's really needed in a project. For the moment the current leverage custom tasks (https://leverage.binbash.com.ar/user-guide/leverage-cli/tasks/) fully covers our current project requirements.   

CC: @binbashar/leverage-ref-architecture-aws-admin @binbashar/leverage-ref-architecture-aws-dev
