### ISSUE TITLE
Provide a way to easily support running tools that are not part of Leverage's toolbox image

### ISSUE THREAD

**Issue by diego-ojeda-binbash** [binbashar/leverage#233]
## Describe the Feature
Say I want to use a tool like git-helm which allows you to use Helm charts right from the source code, without needing a chart registry with my chart in it. If I were to use vainilla Terraform for that, I would have to get git-helm installed on my computer, then set the HELM_BIN environment variable to point to git-helm path, and then run Terraform on a directory that uses the Helm provider.

## Expected Behavior
I'd like to be able to define additional environment variables I need to be included during a Leverage run.
Also, I'd like to be able to instruct Leverage to include additional tools that I have on my computer so they are available during a Terraform execution.

## Use Case

Is your feature request related to a problem/challenge you are trying to solve? Please provide some additional context of why this feature or capability will be valuable.

## Additional Context

* [git-helm](https://github.com/aslafy-z/helm-git/)
* [A related issue on git-helm's repo](https://github.com/aslafy-z/helm-git/issues/101)

**Comment by diego-ojeda-binbash** [comment]
@Franr this is still requiring some more testing from the team, right?

**Comment by Franr** [comment]
@diego-ojeda-binbash I just need someone to review and approve the PR :slightly_smiling_face:
