### ISSUE TITLE
FEATURE | set default branch to main 

### ISSUE THREAD

**Issue by juanmatias** [binbashar/leverage#237]
## Describe the Feature

Recently, the main GIT Repo providers, such Gitlab or Github, switched to use `main` as default branch.

It is a good idea **binbash Leverage** to use such a name for the default branch when creating the project.

## Expected Behavior

Use the new standards when creating a git repo.

**Comment by exequielrafaela** [comment]
For the moment this is just a nice to have. We'll prioritize other issues 1st.
