### ISSUE TITLE
Draft | Create a pre-release workflow for testing candidate releases in a test environment

### ISSUE THREAD

**Issue by diego-ojeda-binbash** [binbashar/leverage#24]
Prior to cutting a new release, we would like to be able to pre-release to PyPi test environment in order to perform manual testing and other validations.

**Comment by exequielrafaela** [comment]
This feature has been integrated by @angelofenoglio through a Github workflow (https://github.com/binbashar/leverage/actions/workflows/build-push-test-package.yml) in the repo. The developer could now access to this workflow and click "run" passing the following configurable parameters to get the testing candidate releases at https://pypi.org/project/leverage/

- Use workflow from: `branch_name`
- "Version to publish (optional): If not given, next patch from latest will be used.

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/18539704/169142256-a7f83d88-6b87-451b-a144-36d2d8d1cd9d.png">

CC: @binbashar/leverage-ref-architecture-aws-admin @binbashar/leverage-ref-architecture-aws-dev
