### ISSUE TITLE
Feature | Refactor credentials setup tasks to favor a better UX

### ISSUE THREAD

**Issue by exequielrafaela** [binbashar/leverage#68]
## What?

- ✅ Ensure the best user experience covering the following use cases: 
   - bootstrap credentials
   - onboard new user
   - rotate credentials

### Design requirements
- The current `leverage credentials` command is useful for the `bootstrap` ones but then for `management` and `security` gets complicated. 
- The process of configuring the different types of AWS credentials needs to be more decoupled.
- It will support the ability to create `management` and `security` credentials without having the `bootstrap` credentials.
- Support the case of renewing creds, for instance a user who already has the credentials in place only needs his programmatic keys to be modified.

## How?

Design proposed by @diego-ojeda-binbash 

```
$ leverage credentials configure
  \ --type [BOOTSTRAP | MANAGEMENT | SECURITY]
  \ [--skip-assumable-roles-setup]
````

1. If type == `BOOTSTRAP`
  - configure a profile for `BOOTSTRAP` in `.aws/credentials` -- read `bootstrap` creds from csv or allow manual input
  - no need to create/update profiles in `.aws/config`
  - verify or show instructions on how to do that

2. If type == (`MANAGEMENT | SECURITY`)
  - configure a profile for `MANAGEMENT` or `SECURITY` in `.aws/credentials` -- read from csv or allow manual input
  - If skip-assumable-roles-setup, do NOT create/update profiles in `.aws/config`
  - If not skip-assumable-roles-setup, do create/update profiles in `.aws/config`

Then one could run:
- `$ leverage credentials configure --type BOOTSTRAP` for when to deploy the LZ
- `$ leverage credentials configure --type MANAGEMENT` to set permanent credentials and roles in `.aws/config` for `management` user
- `$ leverage credentials configure --type SECURITY` same as above but for security
and optionally one can pass the flag `--skip-assumable-roles-setup` to skip the update to the `.aws/config` file that has the roles profiles.

### Considerations
- We still need the `project.yaml` for the `BOOTSTRAP` credentials (there is still no other file that has that info at bootstrap time).
- After everything is deployed we already have the `config/common.tfvars`, that already has the necessary data to set the credentials and we could take it from there.
- We can still use the `project.yaml` for the `BOOTSTRAP`creds but for `MANAGEMENT` and `SECURITY` we can take from the files that will be permanent in the repo line `common.tfvars`.
- In the near future we should let go the `project.yaml`, but at this point it might take a lot of work. 
   - Before being able to remove the `project.yml` please consider that  currently there is data from the `project.yaml` that is needed and we should move it somewhere else, and `common.tfvars` may not be the best option to host that info.
   - But if possible we should try to remove the `project.yaml` and let the `config/common.tfvars` have most of the info.

---
CC: @binbashar/leverage-ref-architecture-aws-dev @binbashar/leverage-ref-architecture-aws-admin

**Comment by angelofenoglio** [comment]
After reviewing the implementation one extra behavior was found to be needed.
If for whatever reason AWS Organizations is unreachable/unresponsive, or if no `management` or `bootstrap` credentials with the required permissions are found to be configured in the system, then the CLI should trust the information found in `config/common.tfvars` regarding accounts and their ids to configure each accounts profiles.
