### ISSUE TITLE
Feature | Support aws cli 2.0 + SSO  

### ISSUE THREAD

**Issue by exequielrafaela** [binbashar/leverage#70]
## What?

- ✅ `leverage` cli should support latest aws cli 2.0 version and SSO auth mechanism 
  - Related Ref Arch issue: https://github.com/binbashar/le-tf-infra-aws/issues/330

## Why?
AWS CLI integration with AWS SSO offers the following benefits:

- Enterprises can enable their developers to sign in using credentials from AWS SSO or Active Directory by connecting AWS SSO to their Active Directory using AWS Directory Service.
- Developers can sign in from the CLI for faster access.
- Developers can list and switch between accounts and roles to which they have assigned access.
- Developers can generate and save named role profiles in their CLI configuration automatically and reference them in the CLI to run commands in desired accounts and roles.
- The CLI manages short-term credentials automatically so developers can start in and stay in the CLI securely without interruption, and run long running scripts.

### Read More

- https://docs.aws.amazon.com/singlesignon/latest/userguide/integrating-aws-cli.html
- https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html

#### How to Setup AWS SSO with JumpCloud Idp
- https://support.jumpcloud.com/support/s/article/Identity-Management-with-AWS-SSO
-  https://docs.aws.amazon.com/singlesignon/latest/userguide/jumpcloud-idp.html

**Comment by angelofenoglio** [comment]
First steps in this issue:
 - Implement SSO relevant Terraform definitions/templates in Ref Arch template repository
 - Implement script to automate the Security credentials and profile generation. To work in a similar fashion to the MFA script.
 
 Some links that may be useful for inspiration/guidelines on how to implement the feature:
  - https://github.com/99designs/aws-vault/blob/master/USAGE.md#aws-single-sign-on-aws-sso
  - https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html

**Comment by angelofenoglio** [comment]
#### SSO Workflow:
1.  `leverage credentials sso configure --role-name {role name}` (`leverage aws sso configure` maybe?):
    1. Check for an AWS CLI profile named `{project short name}-sso`, if the configured role matches with the one given by the user, and if AWS SSO is logged in. If this is not so, create the profile and launch the login sequence via `aws sso login --profile {project short name}-sso`
    2. List the accounts available via `aws sso list-accounts --access-token {token form previous step}` and create profiles in ~/.aws/{project}/config containing the _role name_ and the _account id_ for each account named `{project short name}-sso-{account name}`
2. When running any command such as `leverage tf plan`:
    1. Check if the login token is still valid. If not, ask to login (`leverage aws sso login`?) or configure credentials.
    2. Parse AWS CLI profiles extracting the ones that are of interest.
    3. Parse `config.tf` and `locals.tf` files from the layer to obtain the accounts for which we need to get credentials.
    4. for each in `ii` check if in `iii`
           - Check if configured and valid
           - If not, get credentials for account and role, configure _key id_, _secret key_, _session token_ and expiration
    5. If there are accounts in 2.3 not in 2.2, warn the user that permission for those accounts is missing and bail.
    6. Execute `tf` command.

-----
@exequielrafaela @diego-ojeda-binbash If you happen to find mistakes or think of a correction/optimization to this workflow, please let me know!
