### ISSUE TITLE
Doc | Update README.md detailing zsh shell considerations and workarounds

### ISSUE THREAD

**Issue by exequielrafaela** [binbashar/leverage#9]
## What?
 - Update README.md detailing zsh shell considerations and workarounds.

## Why? 
- There is an issue when you use `leverage` in `zsh` and for example want to pass args to a task: `leverage state_import["import.json"]` or `leverage outout["-json"]`.
The problem is with the square brackets because `zsh` by default interprets glob patterns with all the input that is passed to it.

## Related Info
The workarounds for this are:
- ✅ escape the brackets: `leverage state_import["import.json"]`.
- ✅ wrap the whole task in quotation marks: `leverage "state_import[import.json]"`.
- ✅ or disable the glob patterns for that cmd: `noglob leverage state_import["import.json"]`.
   - the last one can be made more transparent by setting an alias like this: `alias leverage='noglob leverage'`.

📒 **NOTE:**
BTW this issue only occurs for zsh shell users, bash and sh users don't have this problem.

**Comment by diego-ojeda-binbash** [comment]
This should be fixed now: https://github.com/binbashar/leverage#zsh-glob-patterns-zsh-no-matches-found
