### ISSUE TITLE
Feature | AWS SSM start-session integration with leverage + SSO

### ISSUE THREAD

**Issue by fgauchat-binbash** [binbashar/leverage#95]
## What
- The ability to start an SSM session in the terminal via Leverage, integrating SSO and using the profiles generated after running `leverage aws sso configure`
-  The actual command to run from the AWS CLI is `aws ssm start-session  --target instance-id`
- `start-session` is an interactive command that requires the [Session Manager plugin](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html) to be installed on the client machine making the call.

## Why
- As we move forward with the implementation of SSM, it's crucial to have an easy to use tool for handling SSM connections to the instances.
- SSM connections can be used via web browser, but from an operations perspective, it's better to have interactive shell access to cloud resources. This is specially important when trying to get customers to use this SSM approach for managing AWS instances, specifically when taking into considerations all the security and management benefits of the SSM approach.

**Comment by exequielrafaela** [comment]
@fgauchat-binbash thanks for creating this issue, will revisit this feature for our roadmap.

**Comment by angelofenoglio** [comment]
Additional info to look into:
 - SSH-over-SSM: https://luktom.net/en/e1693-ansible-over-aws-systems-manager-sessions-a-perfect-solution-for-high-security-environments
 - Official AWS Ansible via SSM guide: https://aws.amazon.com/blogs/mt/keeping-ansible-effortless-with-aws-systems-manager/
 - SSM Conection Ansible Plugin: https://docs.ansible.com/ansible/latest/collections/community/aws/aws_ssm_connection.html
   - Note: https://github.com/ansible-collections/community.aws/issues/113

**Comment by exequielrafaela** [comment]
@angelofenoglio thanks for adding this valuable info. I'm leaving an extra reference script we've tested to get AWS SSO creds via `leverage` for a post SSM login task >>[leverage-credentials-sso.sh](https://gist.github.com/exequielrafaela/2d963c6f12186a1492f870ce2f9f9dde)<<

**Comment by exequielrafaela** [comment]
For the momento we'll add a SSM section under https://leverage.binbash.co/user-guide/ref-architecture-aws/features/ sharing the following gist as the recommended solutions https://gist.github.com/exequielrafaela/2d963c6f12186a1492f870ce2f9f9dde

**Comment by borland667** [comment]
@exequielrafaela can we create some walkthrough of how this should be used? To better understand the use case :)
